# Generated by Django 5.1.2 on 2024-10-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.FloatField(),
        ),
    ]
