# Generated by Django 5.1.2 on 2024-10-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_shoe_quantity_alter_shoe_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
