# Generated by Django 5.1.2 on 2024-10-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_shoe_image_shoe_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='image_name',
        ),
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
