# Generated by Django 5.1.2 on 2024-10-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_shoe_image_name_shoe_image_alter_shoe_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
