# Generated by Django 5.1.2 on 2024-10-27 02:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_shoe_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='authentication.shoe')),
            ],
        ),
    ]
