# Generated by Django 5.1.2 on 2024-11-10 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_sale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='shoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.shoe'),
        ),
    ]
