# Generated by Django 5.1.2 on 2024-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_sale_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shoe_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
