# Generated by Django 5.1.2 on 2024-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_sale_shoe_category_sale_shoe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='shoe_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
